---

- name: ezjail test
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: False

  vars:
    ansible_connection: paramiko
    ansible_python_interpreter: /usr/local/bin/python2.7


  tasks:
    # quick setup the test environment

    - name: Install python with raw as ansible relies on it
      raw: 'env ASSUME_ALWAYS_YES\=yes pkg install -y python'

    - name: install ezjail
      pkgng: name=ezjail state=present

    - name: start ezjail
      service: name=ezjail state=started enabled=yes

    - name: install basejail
      raw: ls /usr/jails/basejail || ezjail-admin install

    # manage some jails

    - name: test1 create jail
      ezjail: name=test1 state=started ip_addr=lo0|127.0.0.1
      register: result

    - name: test1 check jail count
      raw: ezjail-admin list|wc -l|tr -d ' '
      register: jailcount

    - name: test1 check jail state
      raw: ezjail-admin list|grep 'DR[ ]*[0-9]*[ ]*127.0.0.1[ ]*test1[ ]*/usr/jails/test1'
      register: state

    - name: test2 check jailroot deleted
      raw: ls /usr/jails|grep 'test1'
      register: jailroot

    - name: test1 assert return values
      assert:
        that:
          - "result.changed"
          - "'Jail test1 created and started' == result.msg"
          - "jailcount.stdout_lines[0] == '3'"
          - "state.stdout != ''"
          - "jailroot.stdout != ''"

    - name: test2 delete jail
      ezjail: name=test1 state=absent
      register: result

    - name: test2 check jail count
      raw: ezjail-admin list|wc -l|tr -d ' '
      register: jailcount
      ignore_errors: yes

    - name: test2 check jail state
      raw: ezjail-admin list|grep 'test1'
      register: state
      ignore_errors: yes

    - name: test2 check jailroot deleted
      raw: ls /usr/jails|grep 'test1'
      register: jailroot
      ignore_errors: yes

    - name: test2 assert
      assert:
        that:
          - "result.changed"
          - "'Jail test1 deleted' == result.msg"
          - "jailcount.stdout_lines[0] == '2'"
          - "state.stdout == ''"
          - "jailroot.stdout == ''"

    - name: test3 start jail2
      ezjail: name=test2 state=stopped ip_addr=lo0|127.0.0.1
      register: result

    - name: test1 check jail count
      raw: ezjail-admin list|wc -l|tr -d ' '
      register: jailcount

    - name: test3 check jail state
      raw: ezjail-admin list|grep 'DS[ ]*N\/A[ ]*127.0.0.1[ ]*test2[ ]*/usr/jails/test2'
      register: state

    - name: test3 check jailroot deleted
      raw: ls /usr/jails|grep 'test2'
      register: jailroot

    - name: test3 assert
      assert:
        that:
          - "result.changed"
          - "'Jail test2 created' == result.msg"
          - "jailcount.stdout_lines[0] == '3'"
          - "state.stdout != ''"
          - "jailroot.stdout != ''"

    - name: test4 stop jail
      ezjail: name=test2 state=stopped
      register: result

    - name: test1 check jail count
      raw: ezjail-admin list|wc -l|tr -d ' '
      register: jailcount

    - name: test4 check jail state
      raw: ezjail-admin list|grep 'DS[ ]*N\/A[ ]*127.0.0.1[ ]*test2[ ]*/usr/jails/test2'
      register: state

    - name: test4 check jailroot deleted
      raw: ls /usr/jails|grep 'test2'
      register: jailroot

    - name: test4 assert
      assert:
        that:
          - "not result.changed"
          - "'Jail test2 not changed' == result.msg"
          - "jailcount.stdout_lines[0] == '3'"
          - "state.stdout != ''"
          - "jailroot.stdout != ''"

    - name: test5 start jail
      ezjail: name=test2 state=started
      register: result

    - name: test5 check jail count
      raw: ezjail-admin list|wc -l|tr -d ' '
      register: jailcount

    - name: test5 check jail state
      raw: ezjail-admin list|grep 'DR[ ]*[0-9]*[ ]*127.0.0.1[ ]*test2[ ]*/usr/jails/test2'
      register: state

    - name: test5 check jailroot deleted
      raw: ls /usr/jails|grep 'test2'
      register: jailroot

    - name: test5 assert
      assert:
        that:
          - "result.changed"
          - "'Jail test2 started' == result.msg"
          - "jailcount.stdout_lines[0] == '3'"
          - "state.stdout != ''"
          - "jailroot.stdout != ''"

    - name: test6 start jail
      ezjail: name=test2 state=started ip_addr=lo0|127.0.0.2
      register: result

    - name: test6 check jail count
      raw: ezjail-admin list|wc -l|tr -d ' '
      register: jailcount

    - name: test6 check jail state
      raw: ezjail-admin list|grep 'DR[ ]*[0-9]*[ ]*127.0.0.2[ ]*test2[ ]*/usr/jails/test2'
      register: state

    - name: test6 check jailroot deleted
      raw: ls /usr/jails|grep 'test2'
      register: jailroot

    - name: test6 assert
      assert:
        that:
          - "result.changed"
          - "'Jail test2 ip_addr updated' == result.msg"
          - "jailcount.stdout_lines[0] == '3'"
          - "state.stdout != ''"
          - "jailroot.stdout != ''"

    - name: test7 start jail 2
      ezjail: name=test2 state=started
      register: result

    - name: test7 check jail count
      raw: ezjail-admin list|wc -l|tr -d ' '
      register: jailcount

    - name: test7 check jail state
      raw: ezjail-admin list|grep 'DR[ ]*[0-9]*[ ]*127.0.0.2[ ]*test2[ ]*/usr/jails/test2'
      register: state

    - name: test7 check jailroot deleted
      raw: ls /usr/jails|grep 'test2'
      register: jailroot

    - name: test7 assert
      assert:
        that:
          - "not result.changed"
          - "'Jail test2 not changed' == result.msg"
          - "jailcount.stdout_lines[0] == '3'"
          - "state.stdout != ''"
          - "jailroot.stdout != ''"

    - name: test8 start jail 2
      ezjail: name=test2 state=started enabled=no
      register: result

    - name: test8 check jail count
      raw: ezjail-admin list|wc -l|tr -d ' '
      register: jailcount

    - name: test8 check jail state
      raw: ezjail-admin list|grep 'DRN[ ]*[0-9]*[ ]*127.0.0.2[ ]*test2[ ]*/usr/jails/test2'
      register: state

    - name: test8 check jailroot deleted
      raw: ls /usr/jails|grep 'test2'
      register: jailroot

    - name: test8 assert
      assert:
        that:
          - "result.changed"
          - "'Jail test2 disabled' == result.msg"
          - "jailcount.stdout_lines[0] == '3'"
          - "state.stdout != ''"
          - "jailroot.stdout != ''"

    - name: test9 start jail 2
      ezjail: name=test2 state=stopped enabled=no
      register: result

    - name: test9 check jail count
      raw: ezjail-admin list|wc -l|tr -d ' '
      register: jailcount

    - name: test9 check jail state
      raw: ezjail-admin list|grep 'DSN[ ]*N\/A[ ]*127.0.0.2[ ]*test2[ ]*/usr/jails/test2'
      register: state

    - name: test9 check jailroot deleted
      raw: ls /usr/jails|grep 'test2'
      register: jailroot

    - name: test9 assert
      assert:
        that:
          - "result.changed"
          - "'Jail test2 stopped' == result.msg"
          - "jailcount.stdout_lines[0] == '3'"
          - "state.stdout != ''"
          - "jailroot.stdout != ''"

    - name: test10 delete jail 2
      ezjail: name=test2 state=absent
      register: result

    - name: test10 check jail count
      raw: ezjail-admin list|wc -l|tr -d ' '
      register: jailcount

    - name: test10 check jail state
      raw: ezjail-admin list|grep 'DRN[ ]*[0-9]*[ ]*127.0.0.2[ ]*test2[ ]*/usr/jails/test2'
      register: state
      ignore_errors: true

    - name: test10 check jailroot deleted
      raw: ls /usr/jails|grep 'test2'
      register: jailroot
      ignore_errors: true

    - name: test10 assert
      assert:
        that:
          - "result.changed"
          - "'Jail test2 deleted' == result.msg"
          - "jailcount.stdout_lines[0] == '2'"
          - "state.stdout == ''"
          - "jailroot.stdout == ''"

    - name: test11 create jail 3
      ezjail: name=some-+crazy_.name state=started ip_addr=127.0.0.1
      register: result

    - name: test11 check jail count
      raw: ezjail-admin list|wc -l|tr -d ' '
      register: jailcount

    - name: test11 check jail state
      raw: ezjail-admin list|grep 'DR[ ]*[0-9]*[ ]*127.0.0.1[ ]*some-+crazy_.name[ ]*/usr/jails/some-+crazy_.name'
      register: state

    - name: test11 check jailroot deleted
      raw: ls /usr/jails|grep 'some-+crazy_.name'
      register: jailroot

    - name: test11 assert
      assert:
        that:
          - "result.changed"
          - "'Jail some-+crazy_.name created and started' == result.msg"
          - "jailcount.stdout_lines[0] == '3'"
          - "state.stdout != ''"
          - "jailroot.stdout != ''"

    - name: test12 update jail 3
      ezjail: name=some-+crazy_.name state=started ip_addr=127.0.0.2
      register: result

    - name: test12 check jail count
      raw: ezjail-admin list|wc -l|tr -d ' '
      register: jailcount

    - name: test12 check jail state
      raw: ezjail-admin list|grep 'DR[ ]*[0-9]*[ ]*127.0.0.2[ ]*some-+crazy_.name[ ]*/usr/jails/some-+crazy_.name'
      register: state

    - name: test12 check jailroot deleted
      raw: ls /usr/jails|grep 'some-+crazy_.name'
      register: jailroot

    - name: test12 assert
      assert:
        that:
          - "result.changed"
          - "'Jail some-+crazy_.name ip_addr updated' == result.msg"
          - "jailcount.stdout_lines[0] == '3'"
          - "state.stdout != ''"
          - "jailroot.stdout != ''"

    - name: test13 delete jail 3
      ezjail: name=some-+crazy_.name state=absent
      register: result

    - name: test13 check jail count
      raw: ezjail-admin list|wc -l|tr -d ' '
      register: jailcount

    - name: test13 check jail state
      raw: ezjail-admin list|grep 'DR[ ]*[0-9]*[ ]*127.0.0.2[ ]*some-+crazy_.name[ ]*/usr/jails/some-+crazy_.name'
      register: state
      ignore_errors: yes

    - name: test13 check jailroot deleted
      raw: ls /usr/jails|grep 'some-+crazy_.name'
      register: jailroot
      ignore_errors: yes

    - name: test13 assert
      assert:
        that:
          - "result.changed"
          - "'Jail some-+crazy_.name deleted' == result.msg"
          - "jailcount.stdout_lines[0] == '2'"
          - "state.stdout == ''"
          - "jailroot.stdout == ''"

    - name: test14 create check mode
      ezjail: name=test4 state=started ip_addr=127.0.0.1
      register: result
      check_mode: yes

    - name: test14 check jail count
      raw: ezjail-admin list|wc -l|tr -d ' '
      register: jailcount

    - name: test14 check jail state
      raw: ezjail-admin list|grep 'DR[ ]*[0-9]*[ ]*127.0.0.1[ ]*test4[ ]*/usr/jails/test4'
      register: state
      ignore_errors: yes

    - name: test14 check jailroot deleted
      raw: ls /usr/jails|grep 'test4'
      register: jailroot
      ignore_errors: yes

    - name: test14 assert
      assert:
        that:
          - "result.changed"
          - "'Jail test4 would have been created and started' == result.msg"
          - "jailcount.stdout_lines[0] == '2'"
          - "state.stdout == ''"
          - "jailroot.stdout == ''"

    - name: test15 create jail for delete check mode
      ezjail: name=test4 state=started ip_addr=127.0.0.1

    - name: test15 delete check mode
      ezjail: name=test4 state=absent
      register: result
      check_mode: yes

    - name: test15 check jail count
      raw: ezjail-admin list|wc -l|tr -d ' '
      register: jailcount

    - name: test15 check jail state
      raw: ezjail-admin list|grep 'DR[ ]*[0-9]*[ ]*127.0.0.1[ ]*test4[ ]*/usr/jails/test4'
      register: state

    - name: test13 check jailroot deleted
      raw: ls /usr/jails|grep 'test4'
      register: jailroot

    - name: test15 assert
      assert:
        that:
          - "result.changed"
          - "'Jail test4 would have been deleted' == result.msg"
          - "jailcount.stdout_lines[0] == '3'"
          - "state.stdout != ''"
          - "jailroot.stdout != ''"

    - name: test16 delete check mode
      ezjail: name=test4 state=stopped ip_addr=127.1.1.1 enabled=no
      register: result
      check_mode: yes

    - name: test16 check jail count
      raw: ezjail-admin list|wc -l|tr -d ' '
      register: jailcount

    - name: test16 check jail state
      raw: ezjail-admin list|grep 'DR[ ]*[0-9]*[ ]*127.0.0.1[ ]*test4[ ]*/usr/jails/test4'
      register: state

    - name: test16 check jailroot deleted
      raw: ls /usr/jails|grep 'test4'
      register: jailroot

    - name: test16 assert
      assert:
        that:
          - "result.changed"
          - "'Jail test4 would have been ip_addr updated and stopped and disabled' == result.msg"
          - "jailcount.stdout_lines[0] == '3'"
          - "state.stdout != ''"
          - "jailroot.stdout != ''"

    - name: test17 cleanup
      ezjail: name=test4 state=absent
      register: result

    - name: test17 check jail count
      raw: ezjail-admin list|wc -l|tr -d ' '
      register: jailcount

    - name: test17 check jail state
      raw: ezjail-admin list|grep 'DR[ ]*[0-9]*[ ]*127.0.0.1[ ]*test4[ ]*/usr/jails/test4'
      register: state
      ignore_errors: yes

    - name: test17 check jailroot deleted
      raw: ls /usr/jails|grep 'test4'
      register: jailroot
      ignore_errors: yes

    - name: test17 assert
      assert:
        that:
          - "result.changed"
          - "'Jail test4 deleted' == result.msg"
          - "jailcount.stdout_lines[0] == '2'"
          - "state.stdout == ''"
          - "jailroot.stdout == ''"








